Draft ds-sig charter
operate-first/community pull request #193
Opened 2022-05-24 15:17 UTC by MichaelClifford

This PR includes a draft charter for the DS-SIG that can serve as a starting point for what we want this SIG to be responsible for. It is based heavily on the [DS SIG charter](https://github.com/open-services-group/community/blob/main/sig-data-science/charter.md) in the OSG group. 

I propose we agree on this charter and have it merged first, and in a follow up PR we can update the sigs.yaml and the auto-generated files. 

#192

2022-05-25 16:05 UTC, quaid commented on sig-data-science/charter.md
> +SIG Data Science is responsible for all data science and machine learning related initiatives within the Operate First Community. This includes the development, exploration and communication of  clou
For this suggestion, I'm also splitting the paragraph into a sentence per line to make the diff easier to read:

```suggestion
SIG Data Science is responsible for all data science and machine learning related initiatives within the Operate First community.
This includes the development, exploration, and communication of cloud native machine learning tools and best practices, MLOps, as well as AIOps tools to enhance the services run by the [Open Services Group](https://github.com/open-services-group/community/).
```

2022-05-25 16:21 UTC, quaid commented on sig-data-science/charter.md
> +* Not responsible for any code, notebooks or projects outside of the Operate First Community, and without an associated sub-project initiated by this SIG.
```suggestion
* Not responsible for any code, notebooks, or projects outside of the Operate First community, and without an associated subproject initiated by this SIG.
```

2022-05-25 16:22 UTC, quaid commented on sig-data-science/charter.md
> +* Not responsible for any request for support on any non-open source data or code.
```suggestion
* Not responsible for any request for support on any non-Open Source data or code.
```

2022-05-25 16:22 UTC, quaid commented on sig-data-science/charter.md
> +This sig adheres to the Roles and Organization Management outlined in [governance document](https://github.com/operate-first/community/blob/main/governance.md)
```suggestion
This SIG adheres to the Roles and Organization Management outlined in [governance document](https://github.com/operate-first/community/blob/main/governance.md)
```

2022-05-25 16:28 UTC, quaid requested changes
This is great in substance, just some copyedits.

2022-06-02 17:16 UTC, quaid commented on sig-data-science/charter.md
> +* Support the onboarding of new data science projects.
```suggestion
* Support the onboarding of new Open Source data science projects.
```

2022-06-06 13:33 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommunity).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2022-06-06 18:12 UTC, MichaelClifford commented
@quaid made the grammar updates you suggested. 

Also, made some larger changes after our discussion in the community SIG meeting last week, including updating the sigs.yaml to include the DS SIG.

2022-06-16 17:28 UTC, quaid commented
/lgtm
/approve

2022-06-16 17:29 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/community/pull/193#issuecomment-1157945523" title="Approved">quaid</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/community/blob/main/OWNERS)~~ [quaid]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-16 17:38 UTC, quaid commented
Holding until we get a second chair and more initial members.
/hold

2022-06-16 17:39 UTC, aakankshaduggal reviewed
/lgtm
/approve

2022-06-16 17:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/community/pull/193#pullrequestreview-1009456196" title="Approved">aakankshaduggal</a>*, *<a href="https://github.com/operate-first/community/pull/193#issuecomment-1157945523" title="Approved">quaid</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fcommunity).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/community/blob/main/OWNERS)~~ [quaid]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-16 18:04 UTC, merged